[colors]
[colors.primary]
background = "#050201"
foreground = "#F5F6E7"

[colors.normal]
black   = "#050201"
red     = "#996c60"
green   = "#6f8059"
yellow  = "#888459"
blue    = "#8985ad"
magenta = "#ad869f"
cyan    = "#75a99a"
white   = "#F5F6E7"

[colors.bright]
black   = "#66605c"
red     = "#c28f7f"
green   = "#7b915b"
yellow  = "#999358"
blue    = "#9892c9"
magenta = "#c590b3"
cyan    = "#74bda8"
white   = "#fef7f2"

[colors.cursor]
text   = "#050201"
cursor = "#F5F6E7"
