# UI Colors (extended)
accent = "#8985ad"
cursor = "#F5F6E7"

# Primary colors
foreground = "#F5F6E7"
background = "#050201"

# Selection colors
selection_foreground = "#050201"
selection_background = "#F5F6E7"

# Normal colors (ANSI 0-7)
color0 = "#050201"
color1 = "#996c60"
color2 = "#6f8059"
color3 = "#888459"
color4 = "#8985ad"
color5 = "#ad869f"
color6 = "#75a99a"
color7 = "#F5F6E7"

# Bright colors (ANSI 8-15)
color8 = "#66605c"
color9 = "#c28f7f"
color10 = "#7b915b"
color11 = "#999358"
color12 = "#9892c9"
color13 = "#c590b3"
color14 = "#74bda8"
color15 = "#fef7f2"
