# Background and foreground colors
background = #050201
foreground = #F5F6E7

# Standard colors
palette = 0=#050201
palette = 1=#996c60
palette = 2=#6f8059
palette = 3=#888459
palette = 4=#8985ad
palette = 5=#ad869f
palette = 6=#75a99a
palette = 7=#F5F6E7

# Bright colors
palette = 8=#66605c
palette = 9=#c28f7f
palette = 10=#7b915b
palette = 11=#999358
palette = 12=#9892c9
palette = 13=#c590b3
palette = 14=#74bda8
palette = 15=#fef7f2
