$color = rgba(5, 2, 1, 1)
$inner_color = rgba(5, 2, 1, 0.66)
$outer_color = rgba(173, 134, 159, 1)
$font_color = rgba(245, 246, 231, 1)
$placeholder_color = rgba(245, 246, 231, 0.7)
$check_color = rgba(117, 169, 154, 1)
